### ISSUE TITLE
Proposal submission: RSE program design for equality

### ISSUE THREAD

**Issue by rkdarst** [nordic-rse/meetups#1]
I've been preparing a talk on the relation of RSEs to demographic diversity and equality.  This was one of the key arguments I used to advance the Aalto RSE program, and by being aware of these issues I have noticed some very interesting patterns.  The seed of this was the CodeRefinery collaboration, in this issue: https://github.com/coderefinery/handsonscicomp/issues/8
I'm a bit over developing talks alone, so I am making an issue to develop it collaboratively.

A rough outline:
- How people learn to do scientific computing
- How the university environment and support services can either promote equality among everyone regardless of background, or promote "rich get richer"
- How a RSE program can be designed with equality as a core value
- How we have accomplished that at Aalto and how it allowed us to get started.

I would want help to develop the outline.  I have a fairly complete set of slides already, but they need to be made prettier and fitting it in 20 minutes would be difficult.  I think this could become a keynote with enough work.

**Comment by rkdarst** [comment]
This is my outline so far (likely converted to slides later, or else a document with minipres):
https://docs.google.com/document/d/1koXr8luwt1j780km9yaI-yrMrNXaklLFgA6uYDoEnC0/edit

The general outline is:
- Anecdotes about supporting people
- How people learn computing
- Specific environmental factors I have noticed (curently long list, could be trimmed down)
- What RSEs should do
- How RSE organizations should act
- Discussion time via HackMD

The last bits need more development still.

**Comment by rantahar** [comment]
Closing, this was proposed for the 2020 workshop
