### ISSUE TITLE
Media: watch another RSE related video

### ISSUE THREAD

**Issue by rkdarst** [nordic-rse/meetups#11]
Instead of giving a new talk on every topic, we can find some good recordings of past talks and re-watch them together.  We would use HackMD to ask questions and discuss at the same time we watch them together (I would propose having one person share the video to everyone via screen+audio share, but we need to make sure the quality will be satisfactory).

Here are some videos I have already found that are good, but there are probably other good ones, too:
* Mike Croucher, the rise of the research software engineer: https://www.youtube.com/watch?v=8ZSaAM8hhJ4 (40 min)

**Comment by bast** [comment]
I think this is a good idea and I don't see a reason to not add this to the schedule as parallel "workshop" track since it requires very little preparation. Do you agree? If yes, which session?

**Comment by rantahar** [comment]
Closing, this was proposed for the 2020 workshop
