### ISSUE TITLE
Computational reproducibility and the FAIR principles

### ISSUE THREAD

**Issue by wna-se** [nordic-rse/meetups#13]
I would like to have a discussion on computational reproducibility and the FAIR principles in relation to RSE. In particular I would hope flush out some stories on challenges/solutions related to computational reproducibility – e.g experiences from trying to rerun an analysis on a new system or training/supporting others in reproducible practices. Ultimately being able to drafts some tips/tricks or a checklist of things to consider to address common pain-points. 

Some work on surveying the field is being done in the the Research Data Alliance (RDA), FORCE 11 and ReSA etc. but I still think it would be an interesting discussion to have with a Nordic RSE perspective.

Does this seem like a good topic for a discussion or a blog post?

**Comment by bast** [comment]
Dear Wolmar, thanks for suggesting this! We are looking forward to have this in the program and will build this in together with you. We are aiming at a discussion session which can result in a blog post.

**Comment by bast** [comment]
This is now in the schedule: https://nordic-rse.org/events/2020-online-get-together/#tuesday-december-1st
And it has your name on it but it does not mean it's all on you, just that you could perhaps lead/prepare the discussion? Please let me know if you would prefer a different arrangement. The topic is definitely super.

Please let me/us know if you would like to apply any changes.

Can I use the above good text as starting point for a session abstract?

**Comment by wna-se** [comment]
I can lead/prepare the discussion and please feel free to use the above text as starting point.

**Comment by wna-se** [comment]
@bast Are there any pointers/guidelines on how the Zoom discussions should be structured for the event? And do we have any specific tool for note taking/writing the blog post?

**Comment by bast** [comment]
We will use https://hackmd.io for collaborative notes. Otherwise you can also drop into the prep call that goes for another 30 mins where we can discuss the rest.

**Comment by rantahar** [comment]
Closing, this was proposed for the 2020 workshop
