### ISSUE TITLE
Panel session on RSE careers

### ISSUE THREAD

**Issue by rantahar** [nordic-rse/meetups#14]

**Comment by samumantha** [comment]
Introduction round
All participants: name and current position, "how my daily work relates to RSE" ?
maybe we could ask something fun as well here?

**Comment by samumantha** [comment]
Inspired by Richards email to Keijo:
something about recognition of RSE work?
something about 'is there an RSE career path'?

**Comment by rkdarst** [comment]
- What tensions do you experience between academic metrics (number of
  papers) and your current employment (or future employment)

- What is the biggest win of RSE, that has made some new science
  possible?

- How would you adjust academic education to help people become RSEs -
  or even, to balance out science some?

- What do you know now that you wish someone had told you when you
  began as a researcher.

- Do you think that "RSE" is a good term?

- What points of resistance to RSE careers have you noticed?

- Has anyone ever told you that RSE skills don't matter?

**Comment by bast** [comment]
- How did you find out about "RSE"?
- When did you realize that you like research (as software engineer) or software engineering (as researcher)?
- How can we reach RSEs who don't know that there are other RSEs?
- What tool/language/method/... are you learning right now or wish you had time to do?

**Comment by rantahar** [comment]
Something about career stages, compared to postdoc, lecturer, professor
 - How would a senior RSE differ from a junior RSE?
 - Do you think your title matters for recognizing your skills?
 - How can RSE positions can compete with other academic positions? How about industry positions?

**Comment by rkdarst** [comment]
- What trends in academic funding might lead to more RSEs being needed?
- Do RSEs belong in each group, at the department level, or in university-wide teams?  Should they be academic/research positions or service staff positions?

**Comment by rantahar** [comment]
Closing, this was proposed for the 2020 workshop
