### ISSUE TITLE
Nordic RSE conference session proposal

### ISSUE THREAD

**Issue by mabraham** [nordic-rse/meetups#16]
I have previously given several talks on how good software practice helps build a developer community around a community code, illustrating with object lessons from the long history of GROMACS. If that is of interest for the Nordic RSE conference coming up, I would be happy to contribute that. I envision something lecture style, with opportunity for questions during and/or after.

Some old slides (for a talk with a slightly different angle) can be found at https://pasc18.pasc-conference.org/typo3temp/pasc/conference-2/program/en/files/msa290s1.pdf

**Comment by wikfeldt** [comment]
Thanks for the contribution! We just discussed it and it obviously sounds very relevant for this event. The room we can find in the schedule is in one of the parallel "Discussion sessions/workshops/events" session, i.e. the one on Wednesday at 12:30-13:30 (https://nordic-rse.org/events/2020-online-get-together/#wednesday-december-2nd). It's a full hour but our suggestion would be to prepare a 15-20 minute talk and reserve the rest of the time for an open discussion. 
How does that sound? If you agree, could you send us a short abstract so we can add it to the schedule?

Cheers!

**Comment by bast** [comment]
Also @rantahar for info.

**Comment by mabraham** [comment]
Abstract:

GROMACS is a free, open-source molecular dynamics community code mainly designed for simulations of proteins, lipids, and nucleic acids. It is one of the fastest and most popular scientific software packages available, and can run on central processing units (CPUs) and graphics processing units (GPUs). In this session, Mark Abraham (former development manager of GROMACS) will illustrate software development practices that helped build the GROMACS developer community. Mark will be happy to take any questions you might have, e.g. on how to apply similar ideas to the software projects you are working on.

**Comment by bast** [comment]
Thanks Mark! Please check https://github.com/nordic-rse/nordic-rse.github.io/pull/173 (I was unsure about the title).

Also for better session-balancing (fewer parallel sessions), I placed it 14:00-15:00 but we can change that if the time is not ideal.

**Comment by rantahar** [comment]
Closing, this was proposed for the 2020 workshop
