### ISSUE TITLE
What do you expect from Nordic RSE (discussion session)

### ISSUE THREAD

**Issue by rantahar** [nordic-rse/meetups#3]
A discussion about the purpose and development of Nordic RSE as an organisation.

Should refer to discussion in the first bi-weekly meeting and the document drafted at https://docs.google.com/document/d/1r2YdGZJMgGqZWNA2Itk8Vgdu-XUoR_0iBfB2ovFx-8A/edit#heading=h.s3dqmskt4k0i.

**Comment by rantahar** [comment]
The purpose of this discussion is to solicit input from prospective members.
 a) What kind of activities they think would be useful?
   1. Advocating for X (value of good software, ...)
   2. Networking opportunities, workshops
   3. Exchanging skills
   4. Formalizing the profession (create career structure)

 b) How the group should be organized?
   1. Registered association
   2. Professional organization
   3. Something else

Questions / discussion prods:
 - Do you consider yourself an RSE? Who is an RSE?
 - Would you join the Nordic RSE organization? Are you a member?
 - Why would you join as a member?
 - If you have joined other professional associations, what have they done for you?

**Comment by bast** [comment]
Can I/you put the above good points/purpose into the session notes?

**Comment by rantahar** [comment]
Closing, this was proposed for the 2020 workshop
