### ISSUE TITLE
Other events we would like

### ISSUE THREAD

**Issue by rkdarst** [nordic-rse/meetups#4]
We would like people to submit or lead events on these topics:

Important:

- Country-specific meetups
  - DK
  - EE
  - FI
  - IS
  - LT
  - LV
  - NO
  - SE

Good to have:
- Rust for Science (Radovan?)
- RSH live-meetup as an event (Anne, Radovan, Richard)
- Git crash course
- Going deep into git
- Sphinx for high-quality documentation (Richard could possibly)
- Something from outside of our fields (humanities/social science/etc)

**Comment by rkdarst** [comment]
RSE service in practice - if someone wants to use RSE for their project.  how does it work in practice?  case studies?

Aalto could give this as an example of how it works here (both as case study and as a manual for those here).

**Comment by rantahar** [comment]
Closing, this was proposed for the 2020 workshop
