### ISSUE TITLE
Talk proposal - "my first R package"

### ISSUE THREAD

**Issue by Teebusch** [nordic-rse/meetups#7]
I would like to propose a talk for the online RSE get-together. See draft of abstract below. I'm thinking of submitting as a lightning talk, but pondering whether there's enough interest to make it a 20min talk, instead. I don't know what the rest of the program will be like and how high the standards are for 20min talks.  My thoughts on the format:

- **Lightning talk (2 mins)** is enough time to get the key message across, but won't leave time for any detail.
- **Talk (20 mins)** I could show the things I learned in more detail and introduce some of the R packages that help with package development.

I'd be fine with either format, but was wondering if anyone has any thoughts on this.

----
**What I learned from publishing my first R package, and why you should write one, too.**

The code I write as a researcher is single-user and single-use. It is written iteratively and usually serves a data analysis (wrangling, exploring, modeling, and reporting). It is meant to get things done quickly and will likely never be looked at again. As a result, this code is neither very reusable nor very elegant, and after doing this for a few years I'm not learning many new tricks anymore. Instead, I'm repeating myself and reinforcing my habits - good and bad ones.

In this talk, I want to speak about how writing an R package has helped me break out of this trot, and get a deeper understanding of not just R, but also software engineering best practices. Writing a package has helped me get a better grasp of software architecture, version control, continuous integration, project management, documentation, code profiling, functional and object oriented programming and more. Picking a project outside of my comfort zone has forced me to dive into unknown areas of computer science. Finally, it is a rite of passage for an aspiring software engineer. 

R has a very streamlined ecosystem for package development that is perfect for beginners and makes adhering to best practices easy. That's why I would recommend using R for a first software package. However, writing code that is meant for others to use, will elevate your expertise in any programming language.

----

(The R package I've written is [noah](https://github.com/Teebusch/noah), it is very simple, and is not going to blow any experienced RSE's socks off. The focus of the talk is on the benefits of package authoring from a researcher / data analyst perspective)

**Comment by bast** [comment]
Thanks for the proposal!

**Comment by bast** [comment]
Just confirming also here that we are looking forward to have this in the program and we will together fine-tune the timings (we are still unsure about how much time we have for talks but we are working on it and will agree on this together with you).

**Comment by Teebusch** [comment]
Awesome! Thank you!

**Comment by bast** [comment]
dear Tobias, this is now in the schedule: https://nordic-rse.org/events/2020-online-get-together/#tuesday-december-1st

15 minutes would be ideal from the scheduling point of view. Is this OK for you? Can I use the above text as abstract to put into the session notes?

**Comment by Teebusch** [comment]
Hi @bast, 15 minutes is ok. I submitted an improved abstract through the abstract submission system. Could you use that instead, please? Or just copy it from here:

> This talk is about how writing an R package has helped me leave my comfort zone and level up my R programming skills. The code I write as a researcher is mostly single-user and single-use. Writing and publishing code meant for others has helped me break old habits and get a better grasp of software engineering. R has a very streamlined ecosystem for package development that makes understanding and following best practices easy. I will talk about the things I have learned, why I think writing a package should be a rite of passage for any aspiring research software engineer, and why R is a great tool for this.

**Comment by bast** [comment]
Great! I will take the abstract from the abstract submission system. Thanks!

**Comment by rantahar** [comment]
Closing, this was proposed for the 2020 workshop.
