### ISSUE TITLE
talk or discussion session: "Lessons learned from procuring a fairly large HPC system"

### ISSUE THREAD

**Issue by wikfeldt** [nordic-rse/meetups#8]
Abstract:

Procuring an HPC system - a.k.a. a supercomputer - is a complex and multifaceted task. Before sending out the Request For Proposals the procurer needs to quantify requirements along several dimensions and decide on an acceptable level of risk. Should the tendered system maximize benefit for existing users and use cases, or should possible future user communities and emerging HPC workloads be factored in? Do you prioritize throughput capability or minimizing time to solution for given workloads? How important are acquisition and running costs compared to other measures? Are you willing to invest in future technologies which would require significant refactoring of commonly used HPC simulation software? Which HPC software should be included in the benchmarking suite, and how should benchmark results be scored? This contribution will present a walk through of several aspects of an HPC procurement, from the perspective of an HPC application expert responsible for benchmarking but not involved in high-level decision making. If there’s interest, the presentation can be followed by a discussion session where experiences can be shared and a set of general guidelines summarized.

**Comment by wikfeldt** [comment]
whether this contribution should be considered will depend on how many HPC people will attend the meeting i guess

**Comment by bast** [comment]
This is now in the program. Should I put the abstract into the session page?

**Comment by rantahar** [comment]
Closing, this was proposed for the 2020 workshop
